### ISSUE TITLE
Centrar texto "No existen fechas guardadas"

### ISSUE THREAD

**Issue by angeloraso** [Marigonzalez96/Mood-Moon#15]
- El texto no se ve centrado
- Probar con la propiedad de css "text-align: center"

<img width="150" alt="Screen Shot 2022-01-20 at 23 13 09" src="https://user-images.githubusercontent.com/15707453/150453417-d4ee2116-c33b-4bb1-aa7d-149936b0132d.png">

**Comment by Marigonzalez96** [comment]
Ya esta puesta la propiedad:

--text-align: center;
